[project]
name = "bootstrap"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ansible-lint>=25.12.0",
    "ansible>=11.9.0",
]
