---
- name: Idempotent Installation of a Microsoft Repo Key, Repo, and VSCode
  hosts: localhost
  gather_facts: true

  vars:
    package_name_to_check: "code"
    repo_key_url: "https://packages.microsoft.com/keys/microsoft.asc"
    package_dest: "/tmp/google-chrome-stable_current_amd64.deb"

  tasks:
    - name: End if Host is not Ubuntu
      ansible.builtin.meta: end_play
      when: not ansible_facts["distribution"] == "Ubuntu"

    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto
      no_log: true

    - name: Set a default fact for vscode_is_installed
      ansible.builtin.set_fact:
        vscode_is_installed: false

    - name: Set a actual fact for vscode_is_installed
      ansible.builtin.set_fact:
        vscode_is_installed: true
      when: package_name_to_check in ansible_facts.packages

    - name: VSCode status
      ansible.builtin.debug:
        msg: "VSCode installed: {{ vscode_is_installed }}"

    - name: Download the Microsoft GPG key (ASCII Armored)
      ansible.builtin.get_url:
        url: https://packages.microsoft.com/keys/microsoft.asc
        dest: /tmp/microsoft.asc
        mode: '0644'

    - name: De-Armor the GPG key and place it in the keyrings directory
      become: true
      ansible.builtin.command: >
        gpg --dearmor -o /usr/share/keyrings/microsoft-vscode-keyring.gpg /tmp/microsoft.asc
      args:
        # Ensures this task only runs if the final destination key file doesn't exist, making it idempotent
        creates: /usr/share/keyrings/microsoft-vscode-keyring.gpg

    - name: Remove temporary ASCII key file
      ansible.builtin.file:
        path: /tmp/microsoft.asc
        state: absent

    - name: Add the VSCode repository in deb822 format
      become: true
      ansible.builtin.deb822_repository:
        name: vscode
        types: [deb]
        uris: https://packages.microsoft.com/repos/vscode
        suites: [stable]
        components: [main]
        signed_by: /usr/share/keyrings/microsoft-vscode-keyring.gpg
        state: present
        enabled: true
      when: not vscode_is_installed

    - name: Update cache and upgrade packages using generic package manager
      become: true
      ansible.builtin.package:
        upgrade: true
        update_cache: true
      tags: privileged
      when: not ansible_facts["os_family"] == 'Darwin' and not vscode_is_installed

    - name: Install VSCode package
      become: true
      ansible.builtin.apt:
        name: code
        state: present
